### ISSUE TITLE
text control ruins new form designer

### ISSUE THREAD

**Issue by Ballzer0** [Kokulan365/Simple-Text-Control-PCF#2]
When i drop this control into my form, the new form designer errors out. This started happening around last weekend, have you experienced anything similar?

![image](https://user-images.githubusercontent.com/28560729/96454239-df9da680-121b-11eb-90b0-c4c559672889.png)

**Comment by bwmodular** [comment]
I have the same issue. Clicking 'Technical Details' or 'OK' does nothing, only option is the 'Back' button.
Works fine (thankfully) in the old form designer.

**Comment by Ballzer0** [comment]
I have a case going on with Microsoft support. They told me it's their fault and a hot fix will be deployed next weekend if all goes well.

**Comment by bwmodular** [comment]
Great, thanks v much for letting us know...

**Comment by bwmodular** [comment]
Seems to be working ok now for me in UK (crm11)

**Comment by Ballzer0** [comment]
started working here today to :) so i guess i should close this issue
